name: build-push

on:
  schedule:
    - cron: '40 11 * * *'
  push:
    branches: [ master ]
    pull_request:
      branches: [ master ]

jobs:
  publish:
    name: Publish and push deployer docker image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        deployer: [ '6', '7']
        include:
          # includes a new variable of additionalTag
          # for the matrix leg matching the deployer version
          - deployer: '6'
            downloadUrl: 'https://deployer.org/releases'
          - deployer: '7'
            additionalTag: sebastianhofer86/deployer:latest,
            downloadUrl: 'https://github.com/deployphp/deployer/releases/download'

    steps:
      -
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Get deployer version for phar download
        id: version
        run: |
          echo "DEPLOYER_VERSION=$(git -c 'versionsort.suffix=-' ls-remote --tags https://github.com/deployphp/deployer.git | cut --delimiter='/' --fields=3 | tr '-' '~' | sort --version-sort | grep v${{ matrix.deployer }} | tail --lines=1)" >> $GITHUB_OUTPUT
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ matrix.additionalTag }}sebastianhofer86/deployer:${{ matrix.deployer }}
          build-args: |
            deployer_version=${{ steps.version.outputs.DEPLOYER_VERSION }}
            download_url=${{ matrix.downloadUrl }}
